# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         TVGuide-NL
version:      0.14
version_from: lib/TVGuide/NL.pm
installdirs:  site
requires:
    Carp:                          0
    Data::Dumper:                  0
    Encode:                        0
    File::Spec:                    0
    HTML::Entities:                0
    HTML::TokeParser:              0
    HTML::TreeBuilder:             0
    LWP::UserAgent:                0
    Storable:                      0
    Time::Local:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
